accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/',views.register, name='register'),
    path('add_address/',views.add_address, name='add_address'),
    path('edit_address/<int:id>',views.edit_address, name='edit_address'),
    
    
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('',views.dashboard, name='dashboard'),
    path('verify_otp/',views.verify_otp, name='verify_otp'),


    path('activate/<uidb64>/<token>',views.activate, name='activate'),
    path('my_orders/',views.my_orders,name='my_orders'),
    path('my_addresses/',views.my_addresses,name='my_addresses'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('change_password/',views.change_password,name='change_password'),
    path('order_detail/<order_id>/',views.order_detail,name='order_detail'),
    path('delete_address/<int:add_id>/',views.delete_address,name='delete_address'),


]

carts/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('',views.cart, name='cart'),
    
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('add_cart_ajax/',views.add_cart_ajax,name='add_cart_ajax'),
    path('add_wishlist/',views.add_wishlist,name='add_wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove_wish_item/',views.remove_wish_item, name='remove_wish_item'),
    

    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart, name='remove_cart'),
    path('remove_cart_ajax/',views.remove_cart_ajax, name='remove_cart_ajax'),
    path('remove_cart_item/',views.remove_cart_item, name='remove_cart_item'),

     path('checkout/',views.checkout, name="checkout"),

]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('django_admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    # path('add_product/',views.add_product,name='add_product'),
    
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/',include('accounts.urls')),
    # orders
    path('orders/',include('orders.urls')),
    path('admin/',include('mycartadmin.urls')),
    path('coupon_offers/',include('coupon_offers.urls')),
    
    
]

admin.site.index_title = "FKart"
admin.site.site_header = "FKart Admin"
admin.site.site_title = "Admin"

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

accounts/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.deletion import CASCADE
from django.db.models.fields import EmailField
from django.db.models.fields.related import OneToOneField

# Create your models here.


class MyAccountManager(BaseUserManager):
    def create_user(self,first_name,last_name,username,email,mobile_number,password=None):
        if not email:
            raise ValueError('User must provide a valid email.')
        
        if not username:
            raise ValueError('Provide a unique username.')
        
        if not mobile_number:
            raise ValueError('Prvode a valid mobile number')
        
        else:
            user = self.model(
                email       = self.normalize_email(email),
                username    = username,
                first_name  = first_name,
                last_name   = last_name,
                mobile_number= mobile_number    
            )
            user.set_password(password)
            user.save(using=self._db)
            return user

    def create_superuser(self,first_name,last_name,email,username,mobile_number,password):
        user = self.create_user(
            email           = self.normalize_email(email),
            username        = username,
            password        = password,
            first_name      = first_name,
            last_name       = last_name,
            mobile_number   = mobile_number
            )
        user.is_admin       = True
        user.is_staff       = True
        user.is_active      = True
        user.is_superuser   = True
        
        user.save(using=self._db)
        return user





class Account(AbstractBaseUser):
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    username        = models.CharField(max_length=50, unique = True)
    email           = models.EmailField(max_length=100, unique = True)
    mobile_number    = models.CharField(max_length=50)

    #required fields
    date_joined     = models.DateTimeField(auto_now_add = True)
    last_login      = models.DateTimeField(auto_now=True)
    is_admin        = models.BooleanField(default=False)
    is_staff        = models.BooleanField(default=False)
    is_superuser    = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=False)

    # setting 'email' as the default login parameter
    USERNAME_FIELD  = 'email'
    # setting up the mandatory fields for registration form
    REQUIRED_FIELDS = ['username','first_name','last_name','mobile_number']

    # adding a User Manager to control users - BaseUserManager
    objects = MyAccountManager()

    # Function to show the desired value to be displayed on the table/while printing. 
    # Eg: firstname
    def __str__(self):
        return self.first_name + ' | ' + self.email
    
    def  full_name(self):
        return f'{self.first_name} {self.last_name}'


    # Setting up permissions to user
    def has_perm(self,perm,obj=None):
        return self.is_admin
    
    def has_module_perms(self,app_label):
        return True


class Otp(models.Model):
    otp     = models.IntegerField(null=True,blank=True)
    user    = models.CharField(max_length=100)

    def __unicode__(self):
        return self.user



class Address(models.Model):

    user            = models.ForeignKey(Account,on_delete=models.SET_NULL,null=True)
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    mobile          = models.CharField(max_length=15, blank=True, null=True)
    email           = models.EmailField(max_length=50, blank=True, null=True)    
    address_line_1  = models.CharField(max_length=100,  blank=True, null=True)
    address_line_2  = models.CharField(max_length=100, blank=True)
    city            = models.CharField(max_length=50)
    district        = models.CharField(max_length=50)
    state           = models.CharField(max_length=50)
    country         = models.CharField(max_length=50, blank=True, null=True)
    pincode         = models.CharField(max_length=10,blank=True, null=True) 

    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)
    
    def  full_name(self):
        return f'{self.first_name} {self.last_name}'
        
    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'



class UserProfile(models.Model):
    user            = models.OneToOneField(Account, on_delete=models.CASCADE)
    profile_picture = models.ImageField(blank = True,upload_to = 'userprofile')
    address_line_1  = models.CharField(max_length = 100, blank=True, null=True)
    address_line_2  = models.CharField(max_length = 100, blank=True, null=True)
    city            = models.CharField(max_length = 20, blank=True, null=True)
    state           = models.CharField(max_length = 20, blank=True, null=True)
    country         = models.CharField(max_length = 20, blank=True, null=True)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'
    


    

accounts/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import Account,Address, UserProfile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Enter Password'
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Confirm Password'
    }))

    class Meta:
        model = Account
        fields = ['first_name','last_name','email','mobile_number','password']
        # will generate the username from the email id input

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        
        if password != confirm_password:
            raise forms.ValidationError("Passwords doesn't match.")

    def __init__(self,*args,**kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder']='Enter Firstname'
        self.fields['last_name'].widget.attrs['placeholder']='Enter Lastname'
        self.fields['email'].widget.attrs['placeholder']='Enter valid Email'
        self.fields['mobile_number'].widget.attrs['placeholder']='Enter Mobile Number'
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'
    


class AddAddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ['first_name','last_name','mobile','email','address_line_1','address_line_2','city','district','state','country','pincode']
       



    def __init__(self,*args,**kwargs):
        super(AddAddressForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder']='Enter Firstname'
        self.fields['last_name'].widget.attrs['placeholder']='Enter last name'
        self.fields['mobile'].widget.attrs['placeholder']='Enter Mobile number'
        self.fields['email'].widget.attrs['placeholder']='Enter email address'
        self.fields['address_line_1'].widget.attrs['placeholder']='Enter your address'
        self.fields['address_line_2'].widget.attrs['placeholder']='Enter your address'
        self.fields['city'].widget.attrs['placeholder']='Enter City Name'
        self.fields['district'].widget.attrs['placeholder']='Enter your district'
        self.fields['state'].widget.attrs['placeholder']='Enter State'
        self.fields['country'].widget.attrs['placeholder']='Enter Country'
        self.fields['pincode'].widget.attrs['placeholder']='Enter Pincode'

        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'


class Userform(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'mobile_number')

    def __init__(self,*args,**kwargs):
        super(Userform, self).__init__(*args, **kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'




class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages={'invalid':"Image Files Only"}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('address_line_1','address_line_2','city','state','country','profile_picture')

    def __init__(self,*args,**kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'

templates/accounts/account_verification_email.html
{% autoescape off %}
Hi {{user.first_name}},

Please click on below link to confirm your registration.
http://{{domain}}{% url 'activate' uidb64=uid token=token %}

If you think its not you, please ignore this mail.

{% endautoescape %}

templates/accounts/add_address.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
            {% include 'includes/alerts.html' %}
            <header class="mb-4"><h4 class="card-title">Add Address</h4></header>
            <form id="addAddressForm" action="{% url 'add_address' %}" method="POST">
                {% csrf_token %}

                {{form.as_p}}
                
                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-primary btn-block"> Add Address </button>
                    </div> <!-- form-group// -->      
                        <p style="color: red;">{{form.email.errors}}</p>
                        <p style="color: red;">{{form.non_field_errors}}</p>
                        <!-- {% if field.help_text %}
                            <small style="color:gray">{{field.help_text}}</small>
                        {% endif %}

                        {% for error in field_errors %}
                            <p style="color:red">{{field.help_text}}</p>
                        {% endfor %}
                        {% for error in non_field_errors %}
                            <p style="color:red">{{field.help_text}}</p>
                        {% endfor %} -->
                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <!-- <p class="text-center mt-4">Have an account? <a href="{% url 'login' %}">Log In</a></p> -->
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    <script>

$('#addAddressForm').validate({
rules:{
    first_name:{
        required:true,
        minlength:3,
        },
    last_name:{
        required:true,
        minlength:1,
        },
    email:{
        required:true,
        email:true,
    },
    mobile:{
        required:true,
        digits:true,
        minlength:10,
        maxlength:10.
    },
    address_line_1:{
        required:true,
        minlength:5,
    },
    address_line_2:{
        required:true,
        
    },
    city:{
        required:true,        
    },
    district:{
        required:true,        
    },
    state:{
        required:true,        
    },
    country:{
        required:true,        
    },
    pincode:{
        required:true,        
    },

},
messages:{
    first_name:{
        required:"Enter your First name.",
        minlength:"Minimum 3 characters required.",
        },
    last_name:{
        required:"Enter your Last name",
        minlength:"Minimum 1 characters required.",
        },
    email:{
        required:"Enter your Email ID",
        email:"Please enter a valid Email.",
    },
    mobile:{
        required:"Enter your Mobile Number",
        digits:"Only numbers allowed.",
        minlength:"10 digits needed",
        maxlength:"Maximum 10 digits allowed.",
    },
    address_line_1:{
        required:"Address required.",
        minlength:"Need at least 5 characters.",
    },
    address_line_2:{
        required:"Address required.",
        
    },city:{
        required:"Enter City name",        
    },
    district:{
        required:"Enter District name",        
    },
    state:{
        required:"Enter State name",        
    },
    country:{
        required:"Enter Country name",        
    },
    pincode:{
        required:"Enter Pincode",        
    },

},
})

$('#id_mobile').keyup(validateMaxLength);
function validateMaxLength(){
        var text = $(this).val();
        var maxlength = 10;
        if(maxlength > 0)  
        {
                $(this).val(text.substr(0, maxlength)); 
        }
}
    </script>

{% endblock %}

templates/accounts/edit_address.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block contents %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
            {% include 'includes/alerts.html' %}
            <header class="mb-4"><h4 class="card-title">Edit Address</h4></header>
            <form action="" method="POST">
                {% csrf_token %}

                {{form | crispy }}
                
                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-primary btn-block"> Edit Address </button>
                    </div> 
                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <!-- <p class="text-center mt-4">Have an account? <a href="{% url 'login' %}">Log In</a></p> -->
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}




<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    <!-- {% include 'includes/alerts.html' %} -->

    <div class="container">
        <div class="row">

            {% include 'includes/dashboard_sidebar.html' %}
        <main class="col-md-9">
            <article class="card mb-4">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Edit Your Profile</strong>
                
            </header>
            <div class="card-body">
                <div class="text-center">
                    <img src="{{userprofile.profile_picture.url}}" width="100" style="border-radius: 50%;" alt="Profile Picture">
                </div>
                <div class="row">   
                    <div class="col-md-12">
                        <form action="" id="editProfileForm" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label>First Name</label>
                                    {{user_form.first_name}}
                                </div>
                                <div class="form-group col-md-6">
                                    <label>Last Name</label>
                                    {{user_form.last_name}}
                                </div>
                            </div>
                            <div class="form-row">
                                   <div class="form-group col-md-6">
                                    <label>Mobile No</label>
                                    {{user_form.mobile_number}}
                                </div>
                                <div class="form-group col-md-6">
                                    <label>Profile Picture</label>
                                    {{profile_form.profile_picture}}
                                </div>
                            </div>
                       
                            <div class="form-row">
                                <div class="form-group col-12">
                                    <label>Address Line 1</label>
                                    {{profile_form.address_line_1}}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-12">
                                    <label>Address Line 2 </label>
                                    {{profile_form.address_line_2}}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label>City</label>
                                    {{profile_form.city}}
                                </div>
                                <div class="form-group col-md-4">
                                    <label>State</label>
                                    {{profile_form.state}}
                                </div>
                                    <div class="form-group col-md-4">
                                    <label>Country</label>
                                    {{profile_form.country}}
                                </div>
                            </div>
                            <div>
                             <div class="form-group">
            <div id="image-box" class="image-container"></div>
            <button class="btn btn-outline-info" id="crop-btn" style="width: 100%; margin-top: 10px; display: none;" type="button">Crop</button>
            <button class="btn btn-outline-info" id="confirm-btn" style="width: 100%; margin-top: 10px;" type="submit">Save</button>            
          </div>
                            </div>


                            
                        </form>


                    </div>


                </div> <!-- row.// -->
            </div> <!-- card-body .// -->

            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    <script>


$('#editProfileForm').validate({
rules:{
    first_name:{
        required:true,
        minlength:3,
        },
    last_name:{
        required:true,
        minlength:1,
        },
    email:{
        required:true,
        email:true,
    },
    mobile:{
        required:true,
        digits:true,
        minlength:10,
        maxlength:10.
    },
    address_line_1:{
        required:true,
        minlength:5,
    },
    address_line_2:{
        required:true,
        
    },
    city:{
        required:true,        
    },
    district:{
        required:true,        
    },
    state:{
        required:true,        
    },
    country:{
        required:true,        
    },
    pincode:{
        required:true,        
    },

},
messages:{
    first_name:{
        required:"Enter your First name.",
        minlength:"Minimum 3 characters required.",
        },
    last_name:{
        required:"Enter your Last name",
        minlength:"Minimum 1 characters required.",
        },
    email:{
        required:"Enter your Email ID",
        email:"Please enter a valid Email.",
    },
    mobile_number:{
        required:"Enter your Mobile Number",
        digits:"Only numbers allowed.",
        minlength:"10 digits needed",
        maxlength:"Maximum 10 digits allowed.",
    },
    address_line_1:{
        required:"Address required.",
        minlength:"Need at least 5 characters.",
    },
    address_line_2:{
        required:"Address required.",
        
    },city:{
        required:"Enter City name",        
    },
    district:{
        required:"Enter District name",        
    },
    state:{
        required:"Enter State name",        
    },
    country:{
        required:"Enter Country name",        
    },
    pincode:{
        required:"Enter Pincode",        
    },

},
})

$('#id_mobile_number').keyup(validateMaxLength);
function validateMaxLength(){
        var text = $(this).val();
        var maxlength = 10;
        if(maxlength > 0)  
        {
                $(this).val(text.substr(0, maxlength)); 
        }
}

    </script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>

// image-box is the id of the div element that will store our cropping image preview
const imagebox = document.getElementById('image-box')
      // crop-btn is the id of button that will trigger the event of change original file with cropped file.
const crop_btn = document.getElementById('crop-btn')
// id_image is the id of the input tag where we will upload the image
const input = document.getElementById('id_profile_picture')

var filePath = input.value;
var allowedExtensions =  /(\.jpg|\.jpeg|\.png|\.gif)$/i;
const postForm = document.getElementById('post-form')
  console.log(postForm)

// When user uploads the image this event will get triggered
input.addEventListener('change', (e)=>{
  console.log(input.value)
  const img_data = input.files[0]
  value=img_data.type
  
  if (value == "image/jpeg" || value == "image/jpg" || value == "image/png") {
   
  const url = URL.createObjectURL(img_data)
  imagebox.innerHTML = `<img src="${url}" id="image" style="width:100%;">`
  const image = document.getElementById('image')
  document.getElementById('image-box').style.display = 'block'
  document.getElementById('crop-btn').style.display = 'block'
  document.getElementById('confirm-btn').style.display = 'none'
  const cropper = new Cropper(image, {
  aspectRatio: 1 / 1,
  autoCropArea: 1,
  viewMode: 1,  
  scalable: false,
  zoomable: false,
  movable: false,
  minCropBoxWidth: 200,
  minCropBoxHeight: 200,
  })
  crop_btn.addEventListener('click', ()=>{
    cropper.getCroppedCanvas().toBlob((blob)=>{
      let fileInputElement = document.getElementById('id_profile_picture');
      let file = new File([blob], img_data.name,{type:"image/*", lastModified:new Date().getTime()});
      let container = new DataTransfer();
      container.items.add(file);
      fileInputElement.files = container.files;
      document.getElementById('image-box').style.display = 'none'
      document.getElementById('crop-btn').style.display = 'none'
      document.getElementById('confirm-btn').style.display = 'block'

      });
    });

}else{
  Swal.fire({
  icon: 'error',
  title: 'Not Image',
  text: 'The file is not an image..!! Please upload image',
  })
  
  input.value = '';
  return false;
}

  });

</script>
            
    


{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
            {% include 'includes/alerts.html' %}
            <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
            <form action="{% url 'register' %}" id="registerForm" method="POST">
                {% csrf_token %}

        
                    <div class="form-row">
                        <div class="col form-group" id="firstname">
                            <label>First name</label>
                              {{form.first_name}}
                        </div> <!-- form-group end.// -->
                        <div class="col form-group">
                            <label>Last name</label>
                                {{form.last_name}}
                        </div> <!-- form-group end.// -->
                    </div> <!-- form-row end.// -->
                    
                <!-- form-group end.// -->
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Email</label>
                            {{form.email}}
                            <!-- <small class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                        </div> <!-- form-group end.// -->
                        <div class="form-group col-md-6">
                          <label>Mobile Number</label>
                          {{form.mobile_number}}
                        </div> <!-- form-group end.// -->
                        
                    </div> <!-- form-row.// -->
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Create password</label>
                            {{form.password}}
                        </div> <!-- form-group end.// --> 
                        <div class="form-group col-md-6">
                            <label>Repeat password</label>
                            {{form.confirm_password}}
                        </div> <!-- form-group end.// -->  
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
                    </div> <!-- form-group// -->      
                        <p style="color: red;">{{form.email.errors}}</p>
                        <p style="color: red;">{{form.non_field_errors}}</p>
                        <!-- {% if field.help_text %}
                            <small style="color:gray">{{field.help_text}}</small>
                        {% endif %}

                        {% for error in field_errors %}
                            <p style="color:red">{{field.help_text}}</p>
                        {% endfor %}
                        {% for error in non_field_errors %}
                            <p style="color:red">{{field.help_text}}</p>
                        {% endfor %} -->
                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p class="text-center mt-4">Have an account? <a href="{% url 'login' %}">Log In</a></p>
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>

<script>
$('#registerForm').validate({
rules:{
    first_name:{
        required:true,
        minlength:3,
        },
    last_name:{
        required:true,
        minlength:1,
        },
    email:{
        required:true,
        email:true,
    },
    mobile_number:{
        required:true,
        digits:true,
        minlength:10,
        maxlength:10.
    },
    password:{
        required:true,
        minlength:5,
    },

    confirm_password:{
        required:true,
        
        minlength:5,
        equalTo:"#id_password",
        
    },

},
messages:{
    first_name:{
        required:"Enter your First name.",
        minlength:"Minimum 3 characters required.",
        },
    last_name:{
        required:"Enter your Last name",
        minlength:"Minimum 1 characters required.",
        },
    email:{
        required:"Enter your Email ID",
        email:"Please enter a valid Email.",
    },
    mobile_number:{
        required:"Enter your Mobile Number",
        digits:"Only numbers allowed.",
        minlength:"10 digits needed",
        maxlength:"Maximum 10 digits allowed.",
    },
    password:{
        required:"Password required.",
        minlength:"Need at least 5 characters.",
    },

    confirm_password:{
        required:"Re-enter password",
        equalTo:"The passwords must be the same.",
        minlength:"Must be of same length as of the Password",
        
    },
},
})


$('#id_mobile_number').keyup(validateMaxLength);
function validateMaxLength(){
        var text = $(this).val();
        var maxlength = 10;
        if(maxlength > 0)  
        {
                $(this).val(text.substr(0, maxlength)); 
        }
}
  </script>
    

{% endblock %}