carts/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('',views.cart, name='cart'),
    
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('add_cart_ajax/',views.add_cart_ajax,name='add_cart_ajax'),
    path('add_wishlist/',views.add_wishlist,name='add_wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove_wish_item/',views.remove_wish_item, name='remove_wish_item'),
    

    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart, name='remove_cart'),
    path('remove_cart_ajax/',views.remove_cart_ajax, name='remove_cart_ajax'),
    path('remove_cart_item/',views.remove_cart_item, name='remove_cart_item'),

     path('checkout/',views.checkout, name="checkout"),

]

category/urls.py
from django.urls import path,reverse

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('django_admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    # path('add_product/',views.add_product,name='add_product'),
    
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/',include('accounts.urls')),
    # orders
    path('orders/',include('orders.urls')),
    path('admin/',include('mycartadmin.urls')),
    path('coupon_offers/',include('coupon_offers.urls')),
    
    
]

admin.site.index_title = "FKart"
admin.site.site_header = "FKart Admin"
admin.site.site_title = "Admin"

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('place_order/',views.place_order,name='place_order'),
    path('payments/',views.payments,name='payments'),
    path('order_complete/',views.order_complete, name='order_complete'),
    path('rzp_order_complete/',views.rzp_order_complete, name='rzp_order_complete'),
    path('cod_order_complete/<int:order_number>',views.cod_order_complete, name='cod_order_complete'),
    path('proceed_payment/',views.proceed_payment,name='proceed_payment'),
    path('user_order_cancel/<int:order>',views.user_order_cancel, name='user_order_cancel'),
    path('user_order_return/<int:order>',views.user_order_return, name='user_order_return'),
    
    

    
]

category/models.py
from django.db import models
from django.urls import reverse
from django.urls.converters import SlugConverter

# Create your models here.
class Category(models.Model):
    category_name       = models.CharField(max_length=200, unique=True)
    slug                = models.SlugField(max_length=200, unique=True)
    description         = models.TextField(null=True, blank=True)
    category_image      = models.ImageField(upload_to ='photos/categories',default='no_image.png')



    def __str__(self):
        return self.category_name

    def get_url(self):
        return reverse('products_by_category',args=[self.slug])


    
    class Meta:
        verbose_name        = 'Category'
        verbose_name_plural = 'Categories'

mycartadmin/models.py
from django.db import models

# Create your models here.

class BannerUpdate(models.Model):
    banner_image    = models.ImageField(blank = True,upload_to = 'banner_images')
    banner_name     = models.CharField(max_length=50)
    valid_from      = models.DateTimeField()
    valid_to        = models.DateTimeField()
    is_active       = models.BooleanField()
    created_at      = models.DateTimeField(auto_now_add=True)
 

    def __str__(self):
        return self.banner_name

category/forms.py
from django import forms
from django.db.models import fields
from .models import Category






class CategoryForm(forms.ModelForm):
    category_image = forms.ImageField(required=False, error_messages={'invalid':"Image Files Only"}, widget=forms.FileInput)
    class Meta:
        model = Category
        fields = ('category_name', 'description', 'category_image')

    def __init__(self,*args,**kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

mycartadmin/forms.py
from django import forms
from django.forms import widgets

from .models import BannerUpdate

class DateInput(forms.DateTimeInput):
    input_type = 'date'

class BannerUpdateForm(forms.ModelForm):
    class Meta:
        model = BannerUpdate
        fields = ['banner_image','banner_name','valid_from','valid_to','is_active']
        widgets = {
            'valid_from': DateInput(),
            'valid_to':DateInput(),
        }


        def __init__(self,*args,**kwargs):
                super(BannerUpdateForm, self).__init__(*args, **kwargs)

orders/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','email','phone','address_line_1','address_line_2','country','state','city','order_note']
    

class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['order_number','first_name','last_name','status',]
    

mycartadmin/views.py
from datetime import date
from django import contrib
from django.contrib.auth import authenticate,login,logout
from django.contrib.messages.api import success
from django.forms import forms
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls.conf import path
from django.views.decorators.cache import cache_control
from category.models import Category
from coupon_offers.forms import CategoryOfferForm, CouponApplyForm, ProductOfferForm
from mycartadmin.forms import BannerUpdateForm
from mycartadmin.models import BannerUpdate
from orders.forms import OrderForm, OrderStatusForm
from store.forms import ProductForm, ProductGalleryForms, VariationForm
from category.forms import CategoryForm
from store.models import Product, ProductGallery
from orders.models import Order, OrderProduct, Payment
from accounts.models import Account
from coupon_offers.models import Coupon,ProductOffer,CategoryOffer
import mycartadmin
from django.core.paginator import Paginator
from django.utils.text import slugify
from django.db.models import Avg, Count, Min, Max, Sum,FloatField
from datetime import datetime
from django.db.models import Count, DateTimeField
from django.db.models.functions import Trunc

from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import Paragraph, SimpleDocTemplate, Table, TableStyle
from reportlab.lib import colors


@login_required(login_url='admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def filter_orders(request):
    data = []
    data.append(['Name','Order Number','Phone No','Order Value'])
 
    if request.method == "POST":
        
        from_date = request.POST["from_date"]
        to_date = request.POST["to_date"]
        orders = Order.objects.filter(created_at__range=(from_date, to_date))

        # for order in orders:
        #     data.append([str(order.first_name),str(order.order_number),str(order.phone),str(order.order_total)])

        # print(data)

        # fileName = 'orders.pdf'

        # pdf = SimpleDocTemplate(
        #     fileName,
        #     pagesize = letter,
        # )

        # table = Table(data)
        # print('going to print the data')
        # style = TableStyle([
        #     ('BACKGROUND',(0,0),(4,0),colors.green),
        #     ('TESTCOLOR',(0,0),(-1,0),colors.whitesmoke),
        #     # ('ALIGN',(0,0),(-1,-1),'CENTER'),
        #     # ('ALIGN',(1,0),(-1,-1),'CENTER'),
        #     ('FONTNAME',(0,0),(-1,0),'Courier-Bold'),
        #     ('FONTSIZE',(0,0),(-1,0),14),
            
        #     ('BOTTOMPADDING',(0,0),(-1,0),12),
        #     ('BACKGROUND',(0,1),(-1,-1),colors.beige),
        # ])
        # table.setStyle(style)


        # elems = []
        # elems.append(table)
        # pdf.build(elems)

    context = {
        'orders': orders,
    }

    return render(request, 'mycartadmin/orders.html', context)
    
    

@login_required(login_url='admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def order_report(request):
    #create bytestream buffer
    buf = io.BytesIO()
    # create a canvas
    c = canvas.Canvas(buf,pagesize=letter, bottomup=0)
    #create a text opject for canvas 
    c.setTitle("GreatKart")
    c.setSubject("Orders - Filtered within the give range")

    textobj = c.beginText()
    textobj.setTextOrigin(inch,inch)
    textobj.setFont("Helvetica",12)
    lines = []
    if request.method == "POST":
        
        from_date = request.POST["from_date"]
        to_date = request.POST["to_date"]
        orders = Order.objects.filter(created_at__range=(from_date, to_date))

    for order in orders:
        lines.append([str(order.first_name),str(order.order_number),str(order.phone),str(order.order_total)])


  
    # filename = 'orders.pdf'






    # from here the old items start
    for line in lines:
        textobj.textLine(str(line))


    c.drawText(textobj)
    c.showPage()
    c.save()
    buf.seek(0)


    return FileResponse(buf, as_attachment=True,filename='filtered_orders.pdf')

@login_required(login_url='admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_banners(request):
    banners = BannerUpdate.objects.all()
    context = {
        'banners': banners,
    }

    return render(request, 'mycartadmin/admin_banners.html',context)


# Create your views here.
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_login(request):
        if request.user.is_authenticated:
            if request.user.is_superuser:
            
                return redirect('admin_dashboard')
            else:
                messages.error(request, "You dont have admin privileges to view this page.")
                return redirect('home')
        else:
        
            return render(request,'mycartadmin/login.html')

@login_required(login_url='admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_dashboard(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            
            total_ord_no = Order.objects.all().count()
            total_user_no = Account.objects.all().count()         
            
            total_order_value = Order.objects.all().aggregate(Sum('order_total'))
            # print(total_order_value['order_total__sum'],'total order value')

            avg_ord_value = Order.objects.all().aggregate(average_order_value = Avg('order_total'))
            
            val_diff = Order.objects.aggregate(value_diff = Max('order_total', output_field = FloatField())-Avg('order_total'))
                       
            orders_per_day = Order.objects.annotate(order_day=Trunc('created_at', 'day', output_field=DateTimeField())).values('order_day').annotate(orders=Count('id')).order_by('-order_day')[:7]
            ord_val_per_day = Order.objects.annotate(order_day=Trunc('created_at', 'day', output_field=DateTimeField())).values('order_total').annotate(ord_value=Sum('id')).order_by('-order_day')[:7]
            # qty_product = Order.objects.annotate(num_prod=Count('product'))
            # print(qty_product)
            latest_order = Order.objects.all().order_by('-created_at')[:5]
          
            # sample = OrderProduct.objects.annotate(Sum('quantity'))

            # print(sample)    

            
        
                        
            labels = []
            ord_data = []
            val_data = []
            category = []
            cat_prod_qty = []
            
            pay_method = Order.objects.annotate(pay_method=Count('payment'))
            
            
            prod_in_cat = Category.objects.annotate(prod_count=Count('product'))
            for i in prod_in_cat:
                category.append(i.category_name)
                cat_prod_qty.append(i.prod_count)
        
            


            for ord in orders_per_day:
                # print(ord['order_day'], ord['orders'])
                labels.append(str(ord['order_day'].date()))
                ord_data.append(ord['orders'])

            for val in ord_val_per_day:
                val_data.append(int(val['ord_value']))
            
        
            labels.reverse()
            # val_data.reverse()
            ord_data.reverse()
            try:
                total_order_value = round(total_order_value['order_total__sum'],2)
            except:
                pass
            
            try:
                avg_ord_value = round(avg_ord_value['average_order_value'],2)
            except:
                pass
           

            context = {
                'latest_order':latest_order,
                'category':category,
                'cat_prod_qty':cat_prod_qty,
                'labels':labels,
                'data':ord_data,
                'val_data':val_data,
                'total_user_no':total_user_no,
                'total_ord_no':total_ord_no,
                # 'total_order_value':format(total_order_value['order_total__sum'],".2f"),
                'total_order_value':total_order_value,
                # 'avg_ord_value':format(avg_ord_value['average_order_value'],".2f"),
                'avg_ord_value':avg_ord_value,
                # 'latest_order': latest_order,
                
                }
            return render(request,'mycartadmin/index.html', context)
        else:
            messages.error(request,"You have no admin privileges to view this page")
            return redirect('home')
    else:
        return redirect('admin_login')
    
    


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_page_view(request):
    if request.method == "POST":
        
        username        = request.POST['email']
        password        = request.POST['password']
        admin_user      = authenticate(username=username, password=password)
        

        if admin_user is not None:
            
            if admin_user.is_superuser:
               
                login(request,admin_user)
                
                return redirect('admin_login')
            else:
               
                messages.error(request,"Only Admin can access this page.")
                return redirect('admin_login')
        else:
            messages.error(request,"The login details given are not of any admin user. Please retry with correct details.")
            return redirect('admin_login')
    else:

        return redirect('admin_login')


@login_required(login_url='admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_logout(request):

    logout(request)
   
    return redirect('admin_login')


#rendering various pages on the admin panel

templates/mycartadmin/add_category.html
{% extends 'mycartadmin/admin_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contents %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
       
 
  <div class="card mx-auto" style=" margin-top:10px; margin-bottom:50px ">
            
                
    <div class="row mt-3">
      <div class="col-md-6" style="height: 50%; margin: auto;">
          <form id="addCategoryForm" action="{% url 'add_category' %}" method="POST" enctype="multipart/form-data" id="post-form" >
            {% csrf_token %}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Add Category</legend>
              {% include 'includes/alerts.html' %}
              {{ form | crispy }}
            </fieldset>

            <div class="form-group">
              <div id="image-box" class="image-container"></div>
              <button class="btn btn-outline-info" id="crop-btn" style="width: 100%; margin-top: 10px; display: none;" type="button">Crop</button>
              <button class="btn btn-outline-info" id="confirm-btn" style="width: 100%; margin-top: 10px;" type="submit">Add Category</button>            
            </div>
              </form>


      </div>
    </div>




<script>
$('#addCategoryForm').validate({
rules:{
  category_name:{
    required:true,
    minlength:3,
  },
  description:{
    required:true,
    minlength:3,
  },
  category_image:{
    required:true,
  }, 
},
messages:{
  category_name:{
    required:"Enter a valid category name.",
    minlength:"Minimum 3 characters needed.",
  },
  description:{
    required:"Please add some description.",
    minlength:"Minimum 3 characters needed.",
  },  
  category_image:{
    required:"Select and upload image to represent category.",
  },
 
}
})

</script>

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>

// image-box is the id of the div element that will store our cropping image preview
const imagebox = document.getElementById('image-box')
      // crop-btn is the id of button that will trigger the event of change original file with cropped file.
const crop_btn = document.getElementById('crop-btn')
// id_image is the id of the input tag where we will upload the image
const input = document.getElementById('id_category_image')

var filePath = input.value;
var allowedExtensions =  /(\.jpg|\.jpeg|\.png|\.gif)$/i;
const postForm = document.getElementById('post-form')
  console.log(postForm)

// When user uploads the image this event will get triggered
input.addEventListener('change', (e)=>{
  console.log(input.value)
  const img_data = input.files[0]
  value=img_data.type
  
  if (value == "image/jpeg" || value == "image/jpg" || value == "image/png") {
   
  const url = URL.createObjectURL(img_data)
  imagebox.innerHTML = `<img src="${url}" id="image" style="width:100%;">`
  const image = document.getElementById('image')
  document.getElementById('image-box').style.display = 'block'
  document.getElementById('crop-btn').style.display = 'block'
  document.getElementById('confirm-btn').style.display = 'none'
  const cropper = new Cropper(image, {
  aspectRatio: 1 / 1,
  autoCropArea: 1,
  viewMode: 1,  
  scalable: false,
  zoomable: false,
  movable: false,
  minCropBoxWidth: 200,
  minCropBoxHeight: 200,
  })
  crop_btn.addEventListener('click', ()=>{
    cropper.getCroppedCanvas().toBlob((blob)=>{
      let fileInputElement = document.getElementById('id_category_image');
      let file = new File([blob], img_data.name,{type:"image/*", lastModified:new Date().getTime()});
      let container = new DataTransfer();
      container.items.add(file);
      fileInputElement.files = container.files;
      document.getElementById('image-box').style.display = 'none'
      document.getElementById('crop-btn').style.display = 'none'
      document.getElementById('confirm-btn').style.display = 'block'

      });
    });

}else{
  Swal.fire({
  icon: 'error',
  title: 'Not Image',
  text: 'The file is not an image..!! Please upload image',
  })
  
  input.value = '';
  return false;
}
  });

</script>
            
{% endblock %}

templates/mycartadmin/add_coupon.html
{% extends 'mycartadmin/admin_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contents %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
       
 
    <div class="card mx-auto" style=" margin-top:10px; margin-bottom:50px">
            
                
  <div class="row mt-3">
    <div class="col-md-6" style="height: 50%; margin: auto;">
        <form  action="{% url 'add_coupon' %}" method="POST" enctype="multipart/form-data" id="addCouponForm" style="margin-bottom: 20px;">
          {% csrf_token %}
          <fieldset class="">
            <legend class="border-bottom mb-4">Add Coupon</legend>
            {% include 'includes/alerts.html' %}
            {{ form | crispy }}
          </fieldset>

          <div class="">
            <div id="image-box" class="image-container"></div>
            <button class="btn btn-outline-info" id="crop-btn" style="width: 100%; margin-top: 10px; display: none;" type="button">Crop</button>
            <button class="btn btn-outline-info" id="confirm-btn" style="width: 100%; margin-top: 10px;" type="submit">Add Coupon</button>            
          </div>
          </form>


    </div>
</div>


<script>
  $(document).ready(function() {
    setTimeout(function(){
    
        $('#message').fadeOut('slow')
        },4000)
    })
</script>

<script>
$(document).ready(function(){

jQuery.validator.addMethod("noSpace", function(value, element) { 
  return value.indexOf(" ") < 0 && value != ""; 
}, "No space please and don't leave it empty");
})

$('#addCouponForm').validate({
  rules:{
    code:{
      noSpace:true,
      required:true,
      minlength:5,
      },
    valid_from:{
      required:true,
      
  },
  valid_to:{  
      required:true,
          },
          
  discount:{  
    required:true,
    min:1,
    max:75,
  },       
},
messages:{
  code:{
    required:"Enter a offer name.",
    minlength:"Minimum 5 characters required.",
    },
  valid_from:{
    required:"Select a start date.",  
    },
  valid_to:{  
    required:"Select a end date.",
    },
  discount:{  
    required:"Please add a discount percentage between 1 to 75.",
    min:"Minimum discount is 1%.",
    max:"Maximum of 75% is allowed.",
  },
},
})

</script>


<script>
  var today = new Date();
  var dd = String(today.getDate()).padStart(2, '0');
  var mm = String(today.getMonth() + 1).padStart(2, '0');
  var yyyy = today.getFullYear();

  today = yyyy + '-' + mm + '-' + dd;
  $('#id_valid_from').attr('min', today);
  $('#id_valid_to').attr('min', today);
  document.getElementById('id_valid_from').onchange = e => {
      value = e.target.value
      $('#id_valid_to').attr('min', value);
  }


</script>
            
{% endblock %}

templates/mycartadmin/add_product_offer.html
{% extends 'mycartadmin/admin_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contents %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
       
 
    <div class="card mx-auto" style=" margin-top:10px; margin-bottom:50px">
            
                
  <div class="row mt-3">
    <div class="col-md-6" style="height: 50%; margin: auto;">
        <form action="{% url 'add_product_offer' %}" method="POST" enctype="multipart/form-data" id="addProdOffer" >
          {% csrf_token %}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Product Offer</legend>
            {% include 'includes/alerts.html' %}
            {{ form | crispy }}
          </fieldset>

          <div class="form-group">
            <div id="image-box" class="image-container"></div>
            <button class="btn btn-outline-info" id="crop-btn" style="width: 100%; margin-top: 10px; display: none;" type="button">Crop</button>
            <button class="btn btn-outline-info" id="confirm-btn" style="width: 100%; margin-top: 10px;" type="submit">Add Product Offer</button>            
          </div>
            </form>


    </div>
</div>


<script>
  $('#addProdOffer').validate({
  rules:{
    code:{
      required:true,
      minlength:5,
    },
    product_id:{
      required:true,
    },
    valid_from:{
      required:true,
    },
    valid_to:{  
      required:true,
    },
    discount:{  
      required:true,
      min:1,
      max:75,
    },        
  },
  messages:{
    code:{
      required:"Enter an offer name.",
      minlength:"Minimum 5 characters needed.",
    },
    product_id:{
      required:"Please select Product from the list.",
    },  
    valid_from:{
      required:"Select a start date.",
    },
    valid_to:{  
      required:"Select a end date.",
    },
    discount:{  
      required:"Please add a discount percentage between 1 to 75.",
      min:"Minimum discount is 1%.",
      max:"Maximum of 75% is allowed.",
    },
  }
  })
  
  </script>
  

<!-- date validation part -->
  <script>
    
      var today = new Date();
      var dd = String(today.getDate()).padStart(2, '0');
      var mm = String(today.getMonth() + 1).padStart(2, '0');
      var yyyy = today.getFullYear();
  
      today = yyyy + '-' + mm + '-' + dd;
      $('#id_valid_from').attr('min', today);
      $('#id_valid_to').attr('min', today);
      document.getElementById('id_valid_from').onchange = e => {
          value = e.target.value
          $('#id_valid_to').attr('min', value);
      }
  
  
    </script>
           
{% endblock %}

templates/mycartadmin/edit_cat_offer.html
{% extends 'mycartadmin/admin_base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block contents %}




<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    <!-- {% include 'includes/alerts.html' %} -->

<div class="container">
<div class="row">
<div class="col-md-6" style="height: 50%; margin:auto; margin-top:20px; margin-bottom:50px">

<form action="" method="POST" enctype="multipart/form-data" id="editCatOfferForm" style="margin-bottom: 20px; padding: 30px 20px;">
    {% csrf_token %}
    <fieldset class="form-group">
      
      <legend class="border-bottom mb-4">Edit Category Offer </legend>
      {% include 'includes/alerts.html' %}

      {{ form | crispy }}
    </fieldset>

    <div class="form-group">
      <div id="image-box" class="image-container"></div>
      <button class="btn btn-outline-info" id="crop-btn" style="width: 100%; margin-top: 10px; display: none;" type="button">Crop</button>
      <button class="btn btn-outline-info" id="confirm-btn" style="width: 100%; margin-top: 10px;" type="submit">Update Offer</button>            
    </div>
      </form>
</div>
    </div> <!-- row.// -->
</div> <!-- card-body .// -->

</article> <!-- order-group.// --> 
</main>
</div> <!-- row.// -->
</div>


</section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

<script>

      
$('#editCatOfferForm').validate({
rules:{
  code:{
    required:true,
    minlength:5,
  },
  category_id:{
    required:true,
  },
  valid_from:{
    required:true,
  },
  valid_to:{  
    required:true,
  },
  discount:{  
    required:true,
    min:1,
    max:75,
  },       
},
messages:{
  code:{
    required:"Enter an offer name.",
    minlength:"Minimum 5 characters needed.",
  },
  category_id:{
    required:"Please select category",
  },  
  valid_from:{
    required:"Select a start date.",
  },
  valid_to:{  
    required:"Select a end date.",
  },
  discount:{  
    required:"Please add a discount percentage between 1 to 75.",
    min:"Minimum discount is 1%.",
    max:"Maximum of 75% is allowed.",
  },
}
})


    </script>
    
<script>
  var today = new Date();
  var dd = String(today.getDate()).padStart(2, '0');
  var mm = String(today.getMonth() + 1).padStart(2, '0');
  var yyyy = today.getFullYear();

  today = yyyy + '-' + mm + '-' + dd;
  $('#id_valid_from').attr('min', today);
  $('#id_valid_to').attr('min', today);
  document.getElementById('id_valid_from').onchange = e => {
      value = e.target.value
      $('#id_valid_to').attr('min', value);
  }


</script>
          


{% endblock %}

templates/mycartadmin/edit_product_offer.html
{% extends 'mycartadmin/admin_base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block contents %}




<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">
    <!-- {% include 'includes/alerts.html' %} -->

    <div class="container">
        <div class="row">
    <div class="col-md-6" style="height: 50%; margin: auto;">
        
            <form action="" method="POST" enctype="multipart/form-data" id="editProdOffer" style="margin-bottom: 20px; padding: 30px 20px;">
                {% csrf_token %}
                <fieldset class="form-group">
                  
                  <legend class="border-bottom mb-4">Edit Product Offer</legend>
                  {% include 'includes/alerts.html' %}
                 
                  {{ form | crispy }}
                </fieldset>
      
                <div class="form-group">
                  <div id="image-box" class="image-container"></div>
                  <button class="btn btn-outline-info" id="crop-btn" style="width: 100%; margin-top: 10px; display: none;" type="button">Crop</button>
                  <button class="btn btn-outline-info" id="confirm-btn" style="width: 100%; margin-top: 10px;" type="submit">Update Offer</button>            
                </div>
                  </form>
    </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->

            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    <script>
      $('#editProdOffer').validate({
      rules:{
        code:{
          required:true,
          minlength:5,
        },
        product_id:{
          required:true,
        },
        valid_from:{
          required:true,
        },
        valid_to:{  
          required:true,
        },
        discount:{  
          required:true,
          min:1,
          max:75,
        },       
      },
      messages:{
        code:{
          required:"Enter an offer name.",
          minlength:"Minimum 5 characters needed.",
        },
        product_id:{
          required:"Please select Product from the list.",
        },  
        valid_from:{
          required:"Select a start date.",
        },
        valid_to:{  
          required:"Select a end date.",
        },
        discount:{  
          required:"Please add a discount percentage between 1 to 75.",
          min:"Minimum discount is 1%.",
          max:"Maximum of 75% is allowed.",
        },
      }
      })
      
      </script>
      
    
    <!-- date validation part -->
      <script>
        
          var today = new Date();
          var dd = String(today.getDate()).padStart(2, '0');
          var mm = String(today.getMonth() + 1).padStart(2, '0');
          var yyyy = today.getFullYear();
      
          today = yyyy + '-' + mm + '-' + dd;
          $('#id_valid_from').attr('min', today);
          $('#id_valid_to').attr('min', today);
          document.getElementById('id_valid_from').onchange = e => {
              value = e.target.value
              $('#id_valid_to').attr('min', value);
          }
      
      
        </script>

{% endblock %}